[project]
name = "erpnext_ai"
authors = [
    { name = "PrimeIT", email = "sametyilmaz4444@gmail.com"}
]
description = "ERPNext icin AI asistani"
requires-python = ">=3.10"
readme = "README.md"
dynamic = ["version"]
dependencies = [
    "requests",
]

[build-system]
requires = ["flit_core >=3.4,<4"]
build-backend = "flit_core.buildapi"

[tool.bench.dev-dependencies]
